name: minerva_analysis
channels:
  - conda-forge
dependencies:
  - python=3.7
  - Flask=1.1.2
  - jinja2==3.0.3
  - werkzeug==2.0.3
  - itsdangerous==2.0.1
  - appdirs
  - flask-sqlalchemy
  - numpy
  - ome-types
  - orjson
  - pandas
  - pillow=8.1.1
  - requests
  - scikit-learn
  - scikit-image
  - scipy
  - tifffile=2021.4.8
  - waitress
  - zarr=2.10.3
  - pyinstaller
  - pip
  - pip:
      - opencv-python==4.5.3.56


